=== KualiCo/ojb/src/schema/ojbtest-data.dtd
<!--
#/* Copyright 2004 Apache Software Foundation
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *     http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# */
-->
<!ELEMENT dataset (
    ProductGroup|
    Article|
    Books|
    Cds|
    OrderPosition|
    Tree|
    Treegroup|
    AbTable|
    Product|
    Person|
    Project|
    PersonProject|
    Task|
    FamilyMember|
    LockedByVersion|
    LockedByTimestamp|
    BlobTest|
    MdtestMaster|
    MdtestDetailFkinpk|
    MdtestDetailFknopk|
    Point|
    GraphNode|
    GraphEdge|
    ConversionReferrer|
    ConversionReferred|
    News|
    Paper|
    Topic|
    TopicExt|
    Category|
    Area|
    ContentQualifier|
    SMMaxA|
    SMMaxAA|
    SMMaxAB|
    SMMaxAAA|
    SMMaxB|
    SMMaxBB
    )*>
<!ATTLIST dataset
    name CDATA #REQUIRED
>

<!ELEMENT ProductGroup EMPTY>
<!ATTLIST ProductGroup
    GroupId CDATA #REQUIRED
    GroupName CDATA #IMPLIED
    Description CDATA #IMPLIED
>

<!ELEMENT Article EMPTY>
<!ATTLIST Article
    ArticleId CDATA #REQUIRED
    ArticleName CDATA #IMPLIED
    SupplierId CDATA #IMPLIED
    ProductGroupId CDATA #IMPLIED
    Unit CDATA #IMPLIED
    Price CDATA #IMPLIED
    Stock CDATA #IMPLIED
    OrderedUnits CDATA #IMPLIED
    MinimumStock CDATA #IMPLIED
    InSelloutArticle CDATA #IMPLIED
>

<!ELEMENT Books EMPTY>
<!ATTLIST Books
    ArtikelNr CDATA #REQUIRED
    Artikelname CDATA #IMPLIED
    LieferantenNr CDATA #IMPLIED
    KategorieNr CDATA #IMPLIED
    Liefereinheit CDATA #IMPLIED
    Einzelpreis CDATA #IMPLIED
    Lagerbestand CDATA #IMPLIED
    Bestellteeinheiten CDATA #IMPLIED
    Mindestbestand CDATA #IMPLIED
    Auslaufartikel CDATA #IMPLIED
    Isbn CDATA #IMPLIED
    Author CDATA #IMPLIED
>

<!ELEMENT Cds EMPTY>
<!ATTLIST Cds
    ArtikelNr CDATA #REQUIRED
    Artikelname CDATA #IMPLIED
    LieferantenNr CDATA #IMPLIED
    KategorieNr CDATA #IMPLIED
    Liefereinheit CDATA #IMPLIED
    Einzelpreis CDATA #IMPLIED
    Lagerbestand CDATA #IMPLIED
    Bestellteeinheiten CDATA #IMPLIED
    Mindestbestand CDATA #IMPLIED
    Auslaufartikel CDATA #IMPLIED
    Label CDATA #IMPLIED
    Musicians CDATA #IMPLIED
>

<!ELEMENT OrderPosition EMPTY>
<!ATTLIST OrderPosition
    Id CDATA #REQUIRED
    OrderId CDATA #IMPLIED
    ArticleId CDATA #IMPLIED
>

<!ELEMENT Tree EMPTY>
<!ATTLIST Tree
    Id CDATA #REQUIRED
    Data CDATA #IMPLIED
    ParentId CDATA #IMPLIED
>

<!ELEMENT Treegroup EMPTY>
<!ATTLIST Treegroup
    Id CDATA #REQUIRED
    Data CDATA #IMPLIED
    ParentId CDATA #IMPLIED
    GroupId CDATA #IMPLIED
>

<!ELEMENT AbTable EMPTY>
<!ATTLIST AbTable
    Id CDATA #REQUIRED
    ClassName CDATA #IMPLIED
    Value CDATA #IMPLIED
>

<!ELEMENT Product EMPTY>
<!ATTLIST Product
    _id CDATA #REQUIRED
    Name CDATA #IMPLIED
    Price CDATA #IMPLIED
    Stock CDATA #IMPLIED
>

<!ELEMENT Person EMPTY>
<!ATTLIST Person
    Id CDATA #REQUIRED
    Firstname CDATA #IMPLIED
    Lastname CDATA #IMPLIED
>

<!ELEMENT Project EMPTY>
<!ATTLIST Project
    Id CDATA #REQUIRED
    Title CDATA #IMPLIED
    Description CDATA #IMPLIED
>

<!ELEMENT PersonProject EMPTY>
<!ATTLIST PersonProject
    PersonId CDATA #REQUIRED
    ProjectId CDATA #REQUIRED
    Rolename CDATA #IMPLIED
>

<!ELEMENT Task EMPTY>
<!ATTLIST Task
  TaskId CDATA #REQUIRED
  PersonId CDATA #REQUIRED
  ProjectId CDATA #REQUIRED
  Taskname CDATA #IMPLIED
>

<!ELEMENT FamilyMember EMPTY>
<!ATTLIST FamilyMember
    Id CDATA #REQUIRED
    Firstname CDATA #IMPLIED
    Lastname CDATA #IMPLIED
    MotherId CDATA #IMPLIED
    FatherId CDATA #IMPLIED
>

<!ELEMENT LockedByVersion EMPTY>
<!ATTLIST LockedByVersion
    Id CDATA #REQUIRED
    Value CDATA #IMPLIED
    Version CDATA #IMPLIED
>

<!ELEMENT LockedByTimestamp EMPTY>
<!ATTLIST LockedByTimestamp
    Id CDATA #REQUIRED
    Value CDATA #IMPLIED
    Timestamp CDATA #IMPLIED
>

<!ELEMENT BlobTest EMPTY>
<!ATTLIST BlobTest
    Id CDATA #REQUIRED
    BlobValue CDATA #IMPLIED
    ClobValue CDATA #IMPLIED
>

<!ELEMENT MdtestMaster EMPTY>
<!ATTLIST MdtestMaster
    Masterid CDATA #REQUIRED
    MasterText CDATA #IMPLIED
>

<!ELEMENT MdtestDetailFkinpk EMPTY>
<!ATTLIST MdtestDetailFkinpk
    Masterid CDATA #REQUIRED
    Detailid CDATA #REQUIRED
    DetailText CDATA #IMPLIED
>

<!ELEMENT MdtestDetailFknopk EMPTY>
<!ATTLIST MdtestDetailFknopk
    Detailid CDATA #REQUIRED
    Masterid CDATA #REQUIRED
    DetailText CDATA #IMPLIED
>

<!ELEMENT Point EMPTY>
<!ATTLIST Point
    Id CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
>

<!ELEMENT GraphNode EMPTY>
<!ATTLIST GraphNode
    Id CDATA #REQUIRED
    Name CDATA #REQUIRED
    Location CDATA #IMPLIED
>

<!ELEMENT GraphEdge EMPTY>
<!ATTLIST GraphEdge
    Id CDATA #REQUIRED
    Source CDATA #REQUIRED
    Sink CDATA #REQUIRED
>

<!ELEMENT ConversionReferrer EMPTY>
<!ATTLIST ConversionReferrer
  Pk1 CDATA #REQUIRED
    Ref1 CDATA #IMPLIED
    TestId CDATA #IMPLIED
>

<!ELEMENT ConversionReferred EMPTY>
<!ATTLIST ConversionReferred
  Pk1 CDATA #REQUIRED
    TestId CDATA #IMPLIED
>

<!ELEMENT News EMPTY>
<!ATTLIST News
  Id CDATA #REQUIRED
  Headline CDATA #IMPLIED
>

<!ELEMENT Paper EMPTY>
<!ATTLIST Paper
  Id CDATA #REQUIRED
  Headline CDATA #IMPLIED
  Issuedate CDATA #IMPLIED
  Author CDATA #IMPLIED
>

<!ELEMENT Topic EMPTY>
<!ATTLIST Topic
  Id CDATA #REQUIRED
  Name CDATA #IMPLIED
  Importance CDATA #IMPLIED
>

<!ELEMENT TopicExt EMPTY>
<!ATTLIST TopicExt
  Id CDATA #REQUIRED
  Name CDATA #IMPLIED
  Importance CDATA #IMPLIED
  Description CDATA #IMPLIED
>

<!ELEMENT Category EMPTY>
<!ATTLIST Category
  Id CDATA #REQUIRED
  Name CDATA #IMPLIED
  Description CDATA #IMPLIED
>

<!ELEMENT Area EMPTY>
<!ATTLIST Area
  Id CDATA #REQUIRED
  Name CDATA #IMPLIED
>

<!ELEMENT ContentQualifier EMPTY>
<!ATTLIST ContentQualifier
    ContentId CDATA #REQUIRED
    QualifierId CDATA #REQUIRED
>

<!ELEMENT SMMaxA EMPTY>
<!ATTLIST SMMaxA
    Id CDATA #REQUIRED
    Name CDATA #IMPLIED
>

<!ELEMENT SMMaxAA EMPTY>
<!ATTLIST SMMaxAA
    Id CDATA #REQUIRED
    Name CDATA #IMPLIED
>

<!ELEMENT SMMaxAB EMPTY>
<!ATTLIST SMMaxAB
    Id CDATA #REQUIRED
    Name CDATA #IMPLIED
>

<!ELEMENT SMMaxAAA EMPTY>
<!ATTLIST SMMaxAAA
    Id CDATA #REQUIRED
    Name CDATA #IMPLIED
>

<!ELEMENT SMMaxB EMPTY>
<!ATTLIST SMMaxB
    Id CDATA #REQUIRED
    Name CDATA #IMPLIED
>

<!ELEMENT SMMaxBB EMPTY>
<!ATTLIST SMMaxBB
    Id CDATA #REQUIRED
    Name CDATA #IMPLIED
>

=== KualiCo/ojb/src/schema/ojbtest-data.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!--
#/* Copyright 2002-2004 The Apache Software Foundation
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *     http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# */
-->
<!DOCTYPE dataset SYSTEM "file://ojbtest-data.dtd">
<dataset name="all">

    <ProductGroup GroupId="1" GroupName="Beverages" Description="Alles leckere zum Süffeln"/>
    <ProductGroup GroupId="2" GroupName="Spices" Description="Gewürze, Dressings etc."/>
    <ProductGroup GroupId="3" GroupName="Meat" Description=""/>
    <ProductGroup GroupId="4" GroupName="Liquors" Description=""/>
    <ProductGroup GroupId="5" GroupName="Books" Description="Strange Books..."/>
    <ProductGroup GroupId="6" GroupName="bread" Description=""/>
    <ProductGroup GroupId="7" GroupName="Fruits" Description="Früchte etc."/>
    <ProductGroup GroupId="8" GroupName="Dairy Products" Description="Kat 8"/>
    <ProductGroup GroupId="4711" GroupName="Random Articles" Description="Used for MetadataMultithreadedTest"/>

    <Article ArticleId="1" ArticleName="Chai" SupplierId="1" ProductGroupId="1" Unit="10 boxes x 20 bags" Price="18.53" Stock="39" OrderedUnits="0" MinimumStock="10" InSelloutArticle="0"/>
    <Article ArticleId="2" ArticleName="Chang" SupplierId="1" ProductGroupId="1" Unit="24 - 12 oz bottles" Price="19.89" Stock="17" OrderedUnits="40" MinimumStock="25" InSelloutArticle="0"/>
    <Article ArticleId="3" ArticleName="Aniseed Syrup" SupplierId="1" ProductGroupId="2" Unit="12 - 550 ml bottles" Price="10.2" Stock="13" OrderedUnits="70" MinimumStock="25" InSelloutArticle="0"/>
    <Article ArticleId="4" ArticleName="Chef Antons Cajun Seasoning" SupplierId="2" ProductGroupId="2" Unit="48 - 6 oz jars" Price="22.0" Stock="53" OrderedUnits="0" MinimumStock="0" InSelloutArticle="0"/>
    <Article ArticleId="5" ArticleName="Chef Anton´s Gumbo Mix" SupplierId="2" ProductGroupId="2" Unit="36 boxes" Price="21.35" Stock="0" OrderedUnits="0" MinimumStock="0" InSelloutArticle="1"/>
    <Article ArticleId="6" ArticleName="Grandma´s Boysenberry Spread" SupplierId="3" ProductGroupId="2" Unit="12 - 8 oz jars" Price="25.0" Stock="120" OrderedUnits="0" MinimumStock="25" InSelloutArticle="0"/>
    <Article ArticleId="7" ArticleName="Uncle Bob´s Organic Dried Pears" SupplierId="3" ProductGroupId="7" Unit="12 - 1 lb pkgs." Price="30.0" Stock="15" OrderedUnits="0" MinimumStock="10" InSelloutArticle="0"/>
    <Article ArticleId="8" ArticleName="Northwoods Cranberry Sauce" SupplierId="3" ProductGroupId="2" Unit="12 - 12 oz jars" Price="40.0" Stock="6" OrderedUnits="0" MinimumStock="0" InSelloutArticle="0"/>
    <Article ArticleId="9" ArticleName="Mishi Kobe Niku" SupplierId="4" ProductGroupId="6" Unit="18 - 500 g pkgs." Price="97.0" Stock="29" OrderedUnits="0" MinimumStock="0" InSelloutArticle="1"/>
    <Article ArticleId="10" ArticleName="Ikura" SupplierId="4" ProductGroupId="8" Unit="12 - 200 ml jars" Price="31.0" Stock="31" OrderedUnits="0" MinimumStock="0" InSelloutArticle="0"/>
    <Article ArticleId="11" ArticleName="Queso Cabrales" SupplierId="5" ProductGroupId="4" Unit="1 kg pkg." Price="21.0" Stock="22" OrderedUnits="30" MinimumStock="30" InSelloutArticle="0"/>
    <Article ArticleId="12" ArticleName="Queso Manchego La Pastora" SupplierId="5" ProductGroupId="4" Unit="10 - 500 g pkgs." Price="38.0" Stock="86" OrderedUnits="0" MinimumStock="0" InSelloutArticle="0"/>
    <Article ArticleId="13" ArticleName="Konbu" SupplierId="6" ProductGroupId="8" Unit="2 kg box" Price="6.0" Stock="24" OrderedUnits="0" MinimumStock="5" InSelloutArticle="0"/>
    <Article ArticleId="14" ArticleName="Tofu" SupplierId="6" ProductGroupId="7" Unit="40 - 100 g pkgs." Price="23.25" Stock="35" OrderedUnits="0" MinimumStock="0" InSelloutArticle="0"/>
    <Article ArticleId="15" ArticleName="Genen Shouyu" SupplierId="6" ProductGroupId="2" Unit="24 - 250 ml bottles" Price="15.5" Stock="39" OrderedUnits="0" MinimumStock="5" InSelloutArticle="0"/>
    <Article ArticleId="16" ArticleName="Pavlova" SupplierId="7" ProductGroupId="3" Unit="32 - 500 g boxes" Price="17.45" Stock="29" OrderedUnits="0" MinimumStock="10" InSelloutArticle="0"/>
    <Article ArticleId="17" ArticleName="Alice Mutton" SupplierId="7" ProductGroupId="6" Unit="20 - 1 kg tins" Price="39.0" Stock="0" OrderedUnits="0" MinimumStock="0" InSelloutArticle="1"/>
    <Article ArticleId="18" ArticleName="Carnarvon Tigers" SupplierId="7" ProductGroupId="8" Unit="16 kg pkg." Price="62.5" Stock="42" OrderedUnits="0" MinimumStock="0" InSelloutArticle="0"/>
    <Article ArticleId="19" ArticleName="Teatime Chocolate Biscuits" SupplierId="8" ProductGroupId="3" Unit="10 boxes x 12 pieces" Price="9.2" Stock="25" OrderedUnits="0" MinimumStock="5" InSelloutArticle="0"/>
    <Article ArticleId="20" ArticleName="Sir Rodney´s Marmalade" SupplierId="8" ProductGroupId="3" Unit="30 gift boxes" Price="81.0" Stock="40" OrderedUnits="0" MinimumStock="0" InSelloutArticle="0"/>
    <Article ArticleId="21" ArticleName="Sir Rodney´s Scones" SupplierId="8" ProductGroupId="3" Unit="24 pkgs. x 4 pieces" Price="10.0" Stock="3" OrderedUnits="40" MinimumStock="5" InSelloutArticle="0"/>
    <Article ArticleId="22" ArticleName="Gustaf´s Knäckebröd" SupplierId="9" ProductGroupId="5" Unit="24 - 500 g pkgs." Price="21.0" Stock="104" OrderedUnits="0" MinimumStock="25" InSelloutArticle="0"/>
    <Article ArticleId="23" ArticleName="Tunnbröd" SupplierId="9" ProductGroupId="5" Unit="12 - 250 g pkgs." Price="9.0" Stock="61" OrderedUnits="0" MinimumStock="25" InSelloutArticle="0"/>
    <Article ArticleId="24" ArticleName="Guaraná Fantástica" SupplierId="10" ProductGroupId="1" Unit="12 - 355 ml cans" Price="4.5" Stock="20" OrderedUnits="0" MinimumStock="0" InSelloutArticle="1"/>
    <Article ArticleId="25" ArticleName="NuNuCa Nuß-Nougat-Creme" SupplierId="11" ProductGroupId="3" Unit="20 - 450 g glasses" Price="14.0" Stock="76" OrderedUnits="0" MinimumStock="30" InSelloutArticle="0"/>
    <Article ArticleId="26" ArticleName="Gumbär Gummibärchen" SupplierId="11" ProductGroupId="3" Unit="100 - 250 g bags" Price="31.23" Stock="15" OrderedUnits="0" MinimumStock="0" InSelloutArticle="0"/>
    <Article ArticleId="27" ArticleName="Schoggi Schokolade" SupplierId="11" ProductGroupId="3" Unit="100 - 100 g pieces" Price="43.9" Stock="49" OrderedUnits="0" MinimumStock="30" InSelloutArticle="0"/>
    <Article ArticleId="28" ArticleName="Rössle Sauerkraut" SupplierId="12" ProductGroupId="7" Unit="25 - 825 g cans" Price="45.6" Stock="26" OrderedUnits="0" MinimumStock="0" InSelloutArticle="1"/>
    <Article ArticleId="29" ArticleName="Thüringer Rostbratwurst" SupplierId="12" ProductGroupId="6" Unit="50 bags x 30 sausgs." Price="123.79" Stock="0" OrderedUnits="0" MinimumStock="0" InSelloutArticle="1"/>
    <Article ArticleId="30" ArticleName="Nord-Ost Matjeshering" SupplierId="13" ProductGroupId="8" Unit="10 - 200 g glasses" Price="25.89" Stock="10" OrderedUnits="0" MinimumStock="15" InSelloutArticle="0"/>
    <Article ArticleId="31" ArticleName="Gorgonzola Telino" SupplierId="14" ProductGroupId="4" Unit="12 - 100 g pkgs" Price="12.5" Stock="0" OrderedUnits="70" MinimumStock="20" InSelloutArticle="0"/>
    <Article ArticleId="32" ArticleName="Mascarpone Fabioli" SupplierId="14" ProductGroupId="4" Unit="24 - 200 g pkgs." Price="32.0" Stock="9" OrderedUnits="40" MinimumStock="25" InSelloutArticle="0"/>
    <Article ArticleId="33" ArticleName="Geitost" SupplierId="15" ProductGroupId="4" Unit="500 g" Price="2.5" Stock="112" OrderedUnits="0" MinimumStock="20" InSelloutArticle="0"/>
    <Article ArticleId="34" ArticleName="Sasquatch Ale" SupplierId="16" ProductGroupId="1" Unit="24 - 12 oz bottles" Price="14.0" Stock="111" OrderedUnits="0" MinimumStock="15" InSelloutArticle="0"/>
    <Article ArticleId="35" ArticleName="Steeleye Stout" SupplierId="16" ProductGroupId="1" Unit="24 - 12 oz bottles" Price="18.0" Stock="20" OrderedUnits="0" MinimumStock="15" InSelloutArticle="0"/>
    <Article ArticleId="36" ArticleName="Inlagd Sill" SupplierId="17" ProductGroupId="8" Unit="24 - 250 g  jars" Price="19.0" Stock="112" OrderedUnits="0" MinimumStock="20" InSelloutArticle="0"/>
    <Article ArticleId="37" ArticleName="Gravad lax" SupplierId="17" ProductGroupId="8" Unit="12 - 500 g pkgs." Price="26.0" Stock="11" OrderedUnits="50" MinimumStock="25" InSelloutArticle="0"/>
    <Article ArticleId="38" ArticleName="Côte de Blaye" SupplierId="18" ProductGroupId="1" Unit="12 - 75 cl bottles" Price="263.5" Stock="17" OrderedUnits="0" MinimumStock="15" InSelloutArticle="0"/>
    <Article ArticleId="39" ArticleName="Chartreuse verte" SupplierId="18" ProductGroupId="1" Unit="750 cc per bottle" Price="18.0" Stock="69" OrderedUnits="0" MinimumStock="5" InSelloutArticle="0"/>
    <Article ArticleId="40" ArticleName="Boston Crab Meat" SupplierId="19" ProductGroupId="8" Unit="24 - 4 oz tins" Price="18.4" Stock="123" OrderedUnits="0" MinimumStock="30" InSelloutArticle="0"/>
    <Article ArticleId="41" ArticleName="Jack´s New England Clam Chowder" SupplierId="19" ProductGroupId="8" Unit="12 - 12 oz cans" Price="9.65" Stock="85" OrderedUnits="0" MinimumStock="10" InSelloutArticle="0"/>
    <Article ArticleId="42" ArticleName="Singaporean Hokkien Fried Mee" SupplierId="20" ProductGroupId="5" Unit="32 - 1 kg pkgs." Price="14.0" Stock="26" OrderedUnits="0" MinimumStock="0" InSelloutArticle="1"/>
